services:
  backend:
    build:
      context: ./focus-flow-api
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./focus-flow-api:/app
    command: python app.py
    working_dir: /app
    networks:
      - app-net

  frontend:
    build:
      context: ./focus-flow
    container_name: react_app
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
